AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

  Include:
    - "config.ru"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "app/**/*.rb"
    - "config/**/*.rb"
    - "lib/**/*.rb"
    - "spec/**/*.rb"
    - "db/seeds.rb"

  Exclude:
    - "app/controllers/api/concerns/exception_handler.rb"
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "script/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "app/views/**/*"
    - "lib/origami/origami.rb"

Layout/IndentationConsistency:
  EnforcedStyle: "indented_internal_methods"

Layout/LineLength:
  Max: 80
  Exclude:
    - "config/environments/*"
    - "config/initializers/*"

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "spec/**/*"
    - "Guardfile"
    - "config/environments/*"
    - "config/routes/api.rb"

Metrics/ClassLength:
  Exclude:
    - "db/seeds.rb"
  Max: 165

Metrics/ModuleLength:
  Max: 150

Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"

Naming/MemoizedInstanceVariableName:
  Exclude:
    - "app/controllers/**/*"

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Lint/MissingSuper:
  Exclude:
    - "app/services/**/*"
    - "lib/**/*"
